### ISSUE TITLE
Chapter 5 is Missing

### ISSUE THREAD

**Issue by Chronospades** [BlackTechX011/Termux-Command-Handbook#8]
It seems OP write under Chapter5.md is dedicated to Chapter 4. and then completely forgot Chapter 5 which is the missing one. OP can just create Chapter4.md containing what is Chapter 4 content, While Chapter5.md can be edited to replace current content of it which is the Chapter 4 content.

**Comment by BlackTechX011** [comment]
i will correct it soon
